---
- hosts: localhost
  roles:
    - role: astrap.development

- hosts: all
  tasks:
    - group_by: key=use_gui_{{ use_gui }}
      always_run: True
      tags: [always]
    - group_by: key=use_rvm_{{ use_rvm }}
      always_run: True
      tags: [always]

- hosts: use_gui_True
  roles:
    - role: astrap.gui

- hosts: localhost
  tasks:
    - name: Identify Hardware Product Name
      shell: "dmidecode | grep -A 5 'System Information' | sed -n 's/^\\s*Product Name: //p'"
      become: True
      register: product_name
      always_run: True
      changed_when: False
      tags: [always]
    - group_by: key=product_{{ product_name.stdout }}
      always_run: True
      tags: [always]

- hosts: product_N501VW
  roles:
    - role: astrap.asusux501vw

- hosts: localhost
  roles:
    - role: astrap.android

- hosts: use_rvm_True
  roles:
    - role: rvm_io.ruby
      tags: rvm
      rvm1_user: "{{ansible_user_id}}"
      rvm1_rubies: [ruby-2.3.1]
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_user_id }}/.rvm'


