- name: Prepare bash configs
  template: >
    src={{item}}.j2
    dest="{{astrap_dir}}/.{{item}}"
  with_items:
    - bash_ext
    - bash_ext_local

- name: Install bash configs
  file: >
    state=link
    src="{{astrap_dir}}/.{{item}}"
    dest="{{homedir}}/.{{item}}"
  with_items:
    - bash_ext
    - bash_ext_local

- name: Add bash configs to .bashrc
  lineinfile: >
    regexp="^for bash_file in ~/.bash_ext"
    line="for bash_file in ~/.bash_ext*; do source $bash_file; done"
    dest="{{homedir}}/.bashrc"
