- name: Prepare bash_ext
  template: >
    src=bash_ext.j2
    dest="{{ astrap_dir }}/.bash_ext"

- name: Install bash_ext
  file: >
    state=link
    src="{{ astrap_dir }}/.bash_ext"
    dest="{{ homedir }}/.bash_ext"

