- name: Prepare git files config
  template: >
    src="{{item}}.j2"
    dest="{{astrap_dir}}/.{{item}}"
  with_items:
    - gitconfig
    - gitignore_global

- name: Install git config files
  file: >
    state=link
    src="{{astrap_dir}}/.{{item}}"
    dest="{{homedir}}/.{{item}}"
  with_items:
    - gitconfig
    - gitignore_global

