- name: "GUI: google chrome - authorize key"
  become: True
  apt_key: id=7fac5991 url=https://dl.google.com/linux/linux_signing_key.pub state=present
- name: "GUI: google chrome - add stable repo"
  become: True
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present # filename='google-chrome'
- name: "GUI: google chrome - install"
  become: True
  apt: package=google-chrome-stable state=present update_cache=true

