---
# tasks file for astrap.development
- include: base.yml
  tags:    [base]

- include: ack.yml
  tags:    [ack]

- include: git.yml
  tags:    [git]

- include: bash.yml
  when:    use_bash
  tags:    [bash]

- include: vim.yml
  when:    use_vim
  tags:    [vim]

- include: vim_in_shell.yml
  when:    use_vim_in_shell
  tags:    [vim_in_shell]

- include: nodejs.yml
  when:    use_nodejs
  tags:    [nodejs]

- include: java.yml
  when:    use_java
  tags:    [java]

