- name: "Node.js: add gpg key"
  become: true
  apt_key: >
    id=68576280
    url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state=present

- name: "Node.js: add repository"
  become: true
  apt_repository: >
    repo="deb https://deb.nodesource.com/node_{{nodejs_version}} {{ansible_distribution_release}} main"
    state=present

- name: "Node.js: install"
  become: true
  apt: >
    pkg="nodejs"
    state=installed
    update_cache=yes
