---
# tasks file for astrap.gui
- include: gui.yml
  when:    use_gui and user_only is not defined
  tags:    [gui]

- include: gui_user.yml
  when:    use_gui
  tags:    [gui]

- include: gui_vim.yml
  when:    use_gui
  tags:    [gui]

- include: gui_google-chrome.yml
  when:    use_gui and user_only is not defined
  tags:    [gui,google_chrome]

- include: gui_skype.yml
  when:    use_gui and user_only is not defined
  tags:    [gui,skype]

- include: gui_dropbox.yml
  when:    use_gui and user_only is not defined
  tags:    [gui,dropbox]

- include: gui_spotify.yml
  when:    use_gui and user_only is not defined
  tags:    [gui,spotify]

- include: gui_terminal.yml
  when:    use_gui
  tags:    [gui,gnome_terminal]
